version: "3.9"

services:

  shellbox-pp-api:
    build: ./api
    container_name: shellbox-pp-api
    ports: 
      - 8080:8080

  shellbox-pp-app:
    build: ./app
    container_name: shellbox-pp-app
    ports: 
      - 80:8080
    links: 
      - shellbox-pp-api

volumes: 
  shellbox-pp:
 